Select * from customer limit 20


--SQL questions to find:
-- Q1 : What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2 : Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3 : Which are the top 5 products, with the highest average review ratings?
-- Q4 : Compare the average purchase amounts between standard and express shippings?
-- Q5 : Do subscribed customers spent more? Compare spend and total revenue between subscribers and non-subscribers.
-- Q6 : Which 5 products have the highest percentage of purchases with the discounts applied?
-- Q7 : Segment customers into New, Returning, Loyal based on thier total number of pervious purchases, and show the count of each segment.
-- Q8 : What are the top 3 most purchased products within each category?
-- Q9 : Are customers who are repeat buyers (more than 5 pervious purchases) also likely to subscribe?
-- Q10: What is the revenue contribution of each age group?
